#!/usr/bin/env python

# WS server example

import asyncio
import websockets
import logging
from datetime import datetime

async def hello(websocket, path):
    logger = logging.getLogger()

    name = await websocket.recv()
    logger.warn(f"< {name}")


    greeting = f"Received {name}! This has been generated by the python server and this is a direct websocket communication. as proof, here is a timestamp generated just for this here! {datetime.timestamp(datetime.now())}"

    await websocket.send(greeting)
    logger.warn(f"> HOW YOU DOING?")

if __name__=="__main__":
    logging.basicConfig(level=logging.DEBUG, format='%(message)s')
    logger = logging.getLogger()

    logger.info("Starting Client Side Listener")
    start_server = websockets.serve(hello, "0.0.0.0", 8000)

    asyncio.get_event_loop().run_until_complete(start_server)

    logger.info("Listener Started")
    asyncio.get_event_loop().run_forever()